import type { Context } from "@steve.kite/stdlib";

import type { Compute, ComputeModule } from "../../compute/index.js";
import type { FileReadLog } from "../../impl/FileReadLog.js";

/**
 * Put generated bytes on the agent's machine.
 *
 * Any remembered state is checked again here rather than trusted from before the generation,
 * because a long generation gives whoever else is working on that file plenty of time to save it.
 * Missing directories are created, and the finished file is remembered so a following write can
 * detect an intervening change.
 */
export async function writeGeneratedMediaFile(
    computeModule: ComputeModule,
    compute: Compute,
    reads: FileReadLog,
    ctx: Context,
    path: string,
    bytes: Uint8Array,
): Promise<string> {
    const permissions = computeModule.permissionsForContext(ctx);
    const resolvedPath = computeModule.resolvePath(compute, path);
    await reads.assertRead(ctx, compute.fs, permissions, resolvedPath);
    const parent = computeModule.parentPath(resolvedPath);
    if (parent !== resolvedPath) {
        await compute.fs.mkdir(permissions, parent, { recursive: true });
    }
    await compute.fs.writeFile(permissions, resolvedPath, bytes);
    await reads.record(
        ctx,
        resolvedPath,
        (await compute.fs.stat(permissions, resolvedPath)).mtimeMs,
    );
    return resolvedPath;
}
