export { createHappyPluginClient, HappyPluginApiError } from "./createHappyPluginClient.js";
export { createHappyPluginClient as connectHappy } from "./createHappyPluginClient.js";
export { HappyComputeProviderError } from "./HappyComputeProviderError.js";
export {
    HAPPY_COMPUTE_DEFAULT_COMMAND_TIMEOUT_MS,
    HAPPY_COMPUTE_DEFAULT_PROVISIONING_TIMEOUT_MS,
    HAPPY_COMPUTE_MAX_COMMAND_OUTPUT_BYTES,
    HAPPY_COMPUTE_MAX_COMMAND_TIMEOUT_MS,
    HAPPY_COMPUTE_MAX_FILE_BYTES,
    HAPPY_COMPUTE_MAX_PROVISIONING_TIMEOUT_MS,
    HAPPY_COMPUTE_PROVISIONING_ACK_TIMEOUT_MS,
} from "./computeTypes.js";
export type {
    CreateHappyComputeInput,
    ExecHappyComputeHandlerInput,
    ExecHappyComputeInput,
    HappyComputeError,
    HappyComputeErrorCode,
    HappyComputeEventSubscription,
    HappyComputeExecResult,
    HappyComputeHandlerContext,
    HappyComputeInstance,
    HappyComputeInstanceState,
    HappyComputePreparationEvent,
    HappyComputePreparationPhase,
    HappyComputeProvider,
    HappyComputeProviderContribution,
    HappyComputeProviderHandlers,
    HappyComputeProviderHealth,
    HappyComputeProviderManifest,
    HappyComputeProviderName,
    HappyComputeProvisioningPhase,
    HappyComputeProvisioningProgress,
    HappyComputeRegistration,
    HappyComputeStartHandlerContext,
    HappyComputeWorkspaceSource,
    ReadHappyComputeInput,
    RegisterHappyComputeProviderInput,
    StartHappyComputeHandlerInput,
    StopHappyComputeInput,
    WriteHappyComputeInput,
} from "./computeTypes.js";
export { createHappyMcpToolName, normalizeHappyMcpName } from "./createHappyMcpToolName.js";
export { happyMcpCompletionToResult } from "./happyMcpCompletionToResult.js";
export {
    assertHappyPluginStorageKey,
    assertHappyPluginStorageQuota,
    decodeHappyPluginStorageValue,
    encodeHappyPluginStorageValue,
} from "./pluginAppStorage.js";
export {
    happyPluginAppResourceMediaType,
    isHappyPluginImageMediaType,
} from "./pluginAppResources.js";
export {
    createHappyPluginTestHost,
    type CreateHappyPluginTestHostOptions,
    type HappyPluginTestHost,
} from "./createHappyPluginTestHost.js";
export { defineMcpTool } from "./startHappyMcpServer.js";
export { Type } from "@sinclair/typebox";
export type { Static, TSchema } from "@sinclair/typebox";
export type {
    AgentMessageDelivery,
    ArchiveWorkspaceInput,
    CreateHappyPluginClientOptions,
    CreateHappySlotEntryInput,
    CreateSessionInput,
    CreateWorkspaceInput,
    ExecuteWorkspaceCommandInput,
    ExecuteWorkspaceCommandResponse,
    ExecuteWorkspaceCommandResult,
    HappyPlugin,
    HappyPluginClient,
    HappyPluginAppContribution,
    HappyPluginAppManifest,
    HappyPluginCategory,
    HappyPluginDocker,
    HappyPluginManifest,
    HappyPluginSystemPromptContribution,
    HappyPluginState,
    HappyPluginStreamStatus,
    HappyPluginStatus,
    HappyPluginVersion,
    HappyPluginAppResourceSummary,
    HappyPluginAppSidebar,
    HappyPluginAppToolSummary,
    HappyPluginResourceMediaType,
    HappyMcpCallCompletion,
    HappyMcpContent,
    HappyMcpEvent,
    HappyMcpInputSchema,
    HappyMcpServer,
    HappyMcpServerRegistration,
    HappyMcpServerStatus,
    HappyMcpTool,
    HappyMcpToolContext,
    HappyMcpToolRegistration,
    HappyMcpToolResult,
    HappyNetworkEvent,
    HappyNetworkHeaders,
    HappyNetworkRequest,
    HappyNetworkRequestCompletion,
    HappyNetworkRequestEvent,
    HappyNetworkRequestHandler,
    HappyNetworkRequestResult,
    HappyNetworkSubscription,
    HappyNetworkTunnel,
    HappyNetworkTunnelHandler,
    HappyPluginTestRequest,
    HappyPluginTestSeed,
    HappyProject,
    HappyProviderUsage,
    HappyProviderUsageCredits,
    HappyProviderUsageEntry,
    HappyProviderUsageWindow,
    HappySession,
    HappySystemPromptHook,
    HappySystemPromptHookCompletion,
    HappySystemPromptHookEvent,
    HappySystemPromptHookInput,
    HappySystemPromptHookResult,
    HappySlotAction,
    HappySlotContent,
    HappySlotEntry,
    HappySlotEntryAuthor,
    HappySlotName,
    HappySlotScope,
    HappyWorkspace,
    HappyWorkspaceEvent,
    HappyWorkspaceStatus,
    HappyWorkspaceSubscription,
    HappyTracingEvent,
    HappyTracingSubscription,
    HappyTracingUsage,
    ListWorkspacesInput,
    ListHappySlotEntriesInput,
    PublishHappyMediaInput,
    PublishedHappyMedia,
    ReadWorkspaceFileInput,
    ReadWorkspaceFileResponse,
    ReadWorkspaceFileResult,
    RenameWorkspaceInput,
    SendAgentMessageInput,
    StartHappyMcpServerOptions,
    UpdateHappySlotEntryInput,
    WriteWorkspaceFileInput,
    WriteWorkspaceFileResult,
} from "./types.js";
export {
    agentMessageDeliverySchema,
    archiveWorkspaceBodySchema,
    archiveWorkspaceInputSchema,
    createHappyPluginClientOptionsSchema,
    createHappySlotEntryInputSchema,
    createSessionInputSchema,
    createWorkspaceBodySchema,
    createWorkspaceInputSchema,
    executeWorkspaceCommandBodySchema,
    executeWorkspaceCommandInputSchema,
    executeWorkspaceCommandResponseSchema,
    executeWorkspaceCommandResultSchema,
    happyProjectSchema,
    happyWorkspaceEventSchema,
    happyPluginAppContributionSchema,
    happyPluginAppIdSchema,
    happyPluginAppManifestSchema,
    happyPluginCategorySchema,
    happyPluginDockerSchema,
    happyPluginManifestSchema,
    happyPluginReadyBodySchema,
    happyPluginStatusSchema,
    happyPluginSystemPromptContributionSchema,
    happyPluginVersionSchema,
    happyPluginAppResourceSummarySchema,
    happyPluginAppSidebarSchema,
    happyPluginAppToolSummarySchema,
    happyPluginResourceMediaTypeSchema,
    happyPluginResourcePathSchema,
    happyPluginResourceUriSchema,
    HAPPY_PLUGIN_MAX_ICON_BYTES,
    HAPPY_PLUGIN_MAX_ICON_DIMENSION,
    happyPluginSchema,
    happyPluginStateSchema,
    happyPluginStreamStatusSchema,
    happyProviderUsageCreditsSchema,
    happyProviderUsageEntrySchema,
    happyProviderUsageSchema,
    happyProviderUsageWindowSchema,
    happyMcpCallCompletionSchema,
    happyMcpCallEventSchema,
    happyMcpCancelEventSchema,
    happyMcpContentSchema,
    happyMcpEventSchema,
    happyMcpImageContentSchema,
    happyMcpInputSchemaSchema,
    happyMcpServerRegistrationSchema,
    happyMcpTextContentSchema,
    happyMcpToolRegistrationSchema,
    happyMcpToolResultSchema,
    happyNetworkEventSchema,
    happyNetworkHeadersSchema,
    happyNetworkModifiedRequestSchema,
    happyNetworkPassThroughSchema,
    happyNetworkRequestCompletionSchema,
    happyNetworkRequestEventSchema,
    happyNetworkRequestResultSchema,
    happyNetworkRequestSchema,
    happyNetworkSyntheticResponseSchema,
    happyNetworkTunnelEventSchema,
    happyPluginTestRequestSchema,
    happyPluginTestSeedSchema,
    happySessionSchema,
    happySystemPromptHookCompletionSchema,
    happySystemPromptHookEventSchema,
    happySystemPromptHookInputSchema,
    happySystemPromptHookResultSchema,
    happyTracingEventSchema,
    happyTracingUsageSchema,
    happySlotActionSchema,
    happySlotContentSchema,
    happySlotEntryAuthorSchema,
    happySlotEntryIdSchema,
    happySlotEntryResponseSchema,
    happySlotEntrySchema,
    happySlotNameSchema,
    happySlotScopeSchema,
    happyWorkspaceSchema,
    happyWorkspaceStatusSchema,
    listProjectsResponseSchema,
    listHappyProviderUsageResponseSchema,
    listHappySlotEntriesInputSchema,
    listHappySlotEntriesResponseSchema,
    listPluginsResponseSchema,
    listSessionsResponseSchema,
    listWorkspacesInputSchema,
    listWorkspacesResponseSchema,
    readWorkspaceFileBodySchema,
    readWorkspaceFileInputSchema,
    readWorkspaceFileResponseSchema,
    readWorkspaceFileResultSchema,
    publishHappyMediaBodySchema,
    publishHappyMediaInputSchema,
    publishedHappyMediaSchema,
    renameWorkspaceInputSchema,
    renameWorkspaceBodySchema,
    registerHappyMcpServerResponseSchema,
    registerHappyNetworkListenerResponseSchema,
    registerHappyPluginStreamResponseSchema,
    sendAgentMessageInputSchema,
    sendAgentMessageBodySchema,
    sessionResponseSchema,
    workspaceResponseSchema,
    updateHappySlotEntryInputSchema,
    writeWorkspaceFileBodySchema,
    writeWorkspaceFileInputSchema,
    writeWorkspaceFileResultSchema,
    updateHappyPluginStatusBodySchema,
} from "./types.js";
export {
    HAPPY_PLUGIN_DEFAULT_COMMAND_TIMEOUT_MS,
    HAPPY_PLUGIN_MAX_APPS,
    HAPPY_PLUGIN_MAX_APP_BYTES,
    HAPPY_PLUGIN_MAX_APP_RESOURCES,
    HAPPY_PLUGIN_MAX_COMMAND_OUTPUT_BYTES,
    HAPPY_PLUGIN_MAX_COMMAND_TIMEOUT_MS,
    HAPPY_PLUGIN_MAX_FILE_BYTES,
    HAPPY_PLUGIN_MAX_LIST_ITEMS,
    HAPPY_PLUGIN_MAX_INTERCEPT_DOMAINS,
    HAPPY_PLUGIN_MAX_NETWORK_BODY_BYTES,
    HAPPY_PLUGIN_MAX_NETWORK_EVENT_BYTES,
    HAPPY_PLUGIN_MAX_NETWORK_HEADER_BYTES,
    HAPPY_PLUGIN_MAX_NETWORK_HEADER_COUNT,
    HAPPY_PLUGIN_MAX_NETWORK_HEADER_VALUE_LENGTH,
    HAPPY_PLUGIN_MAX_NETWORK_METHOD_LENGTH,
    HAPPY_PLUGIN_MAX_NETWORK_URL_LENGTH,
    HAPPY_PLUGIN_MAX_MEDIA_BYTES,
    HAPPY_PLUGIN_MAX_RESOURCE_BYTES,
    HAPPY_PLUGIN_MAX_SYSTEM_PROMPT_BYTES,
    HAPPY_PLUGIN_MAX_STORAGE_BYTES,
    HAPPY_PLUGIN_MAX_STORAGE_KEYS,
    HAPPY_PLUGIN_MAX_STORAGE_VALUE_BYTES,
    HAPPY_PLUGIN_TRACING_QUEUE_SIZE,
} from "./types.js";

import { createHappyPluginClient } from "./createHappyPluginClient.js";

/** The plugin's ready-to-use connection to its owning Happy daemon. */
export const happy = createHappyPluginClient();
