import type { SessionUsage } from "@/core/SessionUsage.js";
import type { SessionProviderError } from "@/core/SessionProviderError.js";
import type { SessionOutputBlock } from "@/core/SessionContext.js";

export type {
    SessionProviderError,
    SessionProviderErrorDiagnostics,
} from "@/core/SessionProviderError.js";

export type SessionDoneState = "cancelled" | "normal" | "tool_call" | "length" | "error";

export type SessionErrorKind = "internal_error" | "context_overflow" | "billing_error" | "unknown";

export interface SessionTokens {
    /** Complete input context presented to the model, including cached input. */
    readonly input: number;
    /** Tokens generated by the model. */
    readonly output: number;
}

/** Streaming events emitted during a single session run. */
export type SessionEvent =
    | { type: "block_start" }
    | { type: "block_stop" }
    | { type: "block_reset" }
    | { type: "text_start" }
    | { type: "text_delta"; delta: string }
    | { type: "text_end" }
    | { type: "reasoning_start" }
    | { type: "reasoning_delta"; delta: string }
    | { type: "reasoning_end"; reasoning?: string }
    | {
          type: "toolcall_start";
          callId: string;
          name: string;
          namespace?: string;
          /**
           * The provider ran this call on its own backend and settled it before the response
           * ended. It is reported like any other call, but the client never executes it and never
           * returns a result for it.
           */
          server?: true;
          /** Opaque provider metadata to persist with the tool call and its result. */
          vendor?: any;
      }
    | { type: "toolcall_delta"; callId: string; delta: string }
    | {
          type: "toolcall_end";
          callId: string;
          arguments: string;
          incomplete?: boolean;
          /** Final opaque metadata when it was unavailable at toolcall_start. */
          vendor?: any;
      }
    /**
     * The provider-owned result of a server tool call.
     *
     * Ordinary tools never emit these: the executor answers them and the answer re-enters as a
     * later user/tool message. Server tools settle inside the same response, so their result is
     * streamed here beside the call rather than as work for the client to perform.
     */
    | { type: "toolcall_result_start"; callId: string; vendor?: any }
    | { type: "toolcall_result_delta"; callId: string; delta: string }
    | {
          type: "toolcall_result_end";
          callId: string;
          content: readonly SessionOutputBlock[];
          isError?: boolean;
          incomplete?: boolean;
      }
    | { type: "retrying"; attempt: number; reason: string }
    | { type: "token_usage"; usage: SessionUsage }
    | { type: "done"; state: "cancelled" }
    | { type: "done"; state: "normal"; tokens: SessionTokens; endTurn?: boolean }
    | { type: "done"; state: "tool_call"; tokens: SessionTokens }
    | { type: "done"; state: "length"; tokens: SessionTokens }
    | {
          type: "done";
          state: "error";
          kind: SessionErrorKind;
          message: string;
          providerError?: SessionProviderError;
      };

export type SessionStream = AsyncIterable<SessionEvent>;

export function isSessionDoneEvent(
    event: SessionEvent,
): event is Extract<SessionEvent, { type: "done" }> {
    return event.type === "done";
}

export function isSessionErrorDone(
    event: SessionEvent,
): event is Extract<SessionEvent, { type: "done"; state: "error" }> {
    return event.type === "done" && event.state === "error";
}
