export {
    connectRig,
    ProjectRegistrationError,
    ProjectRegistrationProtocolError,
} from "./connectRig.js";
export {
    discoverRigInstallation,
    DEFAULT_INSTALLATION_DISCOVERY_TIMEOUT_MS,
    MAXIMUM_INSTALLATION_RESPONSE_BYTES,
    RigInstallationDiscoveryHttpError,
    RigInstallationDiscoveryTimeoutError,
    RigInstallationDiscoveryUnsupportedError,
    rigInstallationCompatibility,
} from "./discoverRigInstallation.js";
export type { DiscoverRigInstallationOptions } from "./discoverRigInstallation.js";
export {
    localRigOnboardingInspectionSchema,
    resolveRigOnboarding,
    rigOnboardingStateSchema,
} from "./resolveRigOnboarding.js";
export type {
    LocalRigOnboardingInspection,
    ResolveRigOnboardingOptions,
    RigOnboardingState,
} from "./resolveRigOnboarding.js";
export {
    rigCliInstallationInspectionSchema,
    rigDaemonInstallationDiscoverySchema,
    rigInstallationCliDataSchema,
} from "./RigInstallationInspection.js";
export type {
    RigCliInstallationInspection,
    RigDaemonInstallationDiscovery,
} from "./RigInstallationInspection.js";
export type {
    ConnectRigOptions,
    CreateSessionInput,
    CreateRemoteProjectInput,
    CreateWorkspaceInput,
    DraftUpdate,
    DocumentCreateOptions,
    DocumentUpdatesLoadOptions,
    FolderCreateOptions,
    FolderItemLinkOptions,
    GoalStatus,
    GroupTarget,
    HappyCloudCommandInput,
    HappyCloudOperationOptions,
    ModelSelection,
    ProjectAddOptions,
    RigConnection,
    RigDocumentConnection,
    RigDocumentSubscriptionOptions,
    RigDocuments,
    RigFolders,
    RigFoldersConnection,
    RigFoldersSubscriptionOptions,
    RigProjects,
    RigGroupsConnection,
    RigGroupsSubscriptionOptions,
    RigHappyCloudConnection,
    RigHappyCloudSubscriptionOptions,
    RigP2pConnection,
    RigP2pSubscriptionOptions,
    RigProfilesConnection,
    RigProfilesSubscriptionOptions,
    RigSharingConnection,
    RigSharingSubscriptionOptions,
    RigInboxConnection,
    RigInboxSubscriptionOptions,
    RigProviderUsageConnection,
    RigProviderUsageSubscriptionOptions,
    RigPluginsConnection,
    RigPluginsSubscriptionOptions,
    RigSessionConnection,
    RigSessionSubscriptionOptions,
    RigTimelineConnection,
    RigTimelineSubscriptionOptions,
    RigWorkletsConnection,
    RigWorkletsSubscriptionOptions,
    InstallWorkletInput,
    UpdateWorkletInput,
    SendContextMessageInput,
    SendMessageInput,
    SessionFinished,
    SecretAttachmentScope,
    SecretOperationOptions,
    ShellCommandInput,
    TerminalPresence,
    UserInputAnswers,
} from "./connectRig.js";
export type { SecretRegistration, SecretSummary, SecretUpdate } from "./protocol.js";
export {
    PluginAppRequestError,
    PluginCatalogRequestError,
    PluginIconRequestError,
    PluginManagementRequestError,
    PluginStore,
} from "./PluginElement.js";
export { WorkletManagementRequestError, WorkletStore } from "./WorkletElement.js";
export type {
    ReadWorkletLogResult,
    Worklet,
    WorkletFailure,
    WorkletManagementRequestErrorCode,
    WorkletTool,
    WorkletVersion,
    WorkletsState,
} from "./WorkletElement.js";
export type {
    LocalPlugin,
    PluginApp,
    PluginAppResource,
    PluginCatalogFailure,
    PluginCatalogRequestErrorCode,
    PluginIconRequestErrorCode,
    PluginManagementRequestErrorCode,
    PluginsState,
    ReadPluginAppResourceResult,
    ReadPluginIconResult,
} from "./PluginElement.js";
export type {
    HappyCloudCapability,
    HappyCloudCapabilityStatus,
    HappyCloudChangedEvent,
    HappyCloudCommand,
    HappyCloudCommandErrorResponse,
    HappyCloudCommandResponse,
    HappyCloudConsent,
    HappyCloudProfileCiphertextResponse,
    HappyCloudSessionBlobResponse,
    HappyCloudStatus,
    P2pStatus,
    P2pStatusChangedEvent,
    OnboardMurmurRequest,
    OnboardMurmurResponse,
    OnboardingStatus,
    CreateP2pInvitationResponse,
    JoinP2pInvitationResponse,
    P2pPairingState,
    CreateRigProfileRequest,
    CreateFolderShareRequest,
    ListRigProfilesResponse,
    RigProfile,
    RigProfileChangedEvent,
    RigProfilePhoto,
    RigProfilePhotoInput,
    RigProfileResponse,
    UpdateRigProfileRequest,
    SharingChangedEvent,
    SharingConnection,
    SharingContact,
    SharingContactRequest,
    FolderShareStatus,
    SharingIdentity,
    SharingOutgoingContactRequest,
    SharingSnapshot,
    CreateSharingInvitationResponse,
    InstalledPluginSummary,
    DiscoverPluginCatalogRequest,
    GitHubPluginCatalog,
    GitHubPluginCatalogEntry,
    GitHubPluginPackageSource,
    PluginCatalogErrorCode,
    PluginInstallClassification,
    PluginManagementErrorCode,
    UninstalledPluginSummary,
} from "./protocol.js";
export { FolderStore } from "./FolderStore.js";
export type {
    FolderChild,
    FolderDelta,
    FolderNode,
    FolderSession,
    FolderView,
    FoldersState,
} from "./FolderElement.js";
export { DocumentStore } from "./DocumentStore.js";
export type { DocumentDelta, DocumentState, DocumentUpdatesState } from "./DocumentElement.js";
export { InboxStore } from "./InboxStore.js";
export { ProviderUsageStore } from "./ProviderUsageStore.js";
export type { ProviderUsageDelta, ProviderUsageState } from "./ProviderUsageElement.js";
export type { InboxDelta, InboxItem, InboxState } from "./InboxElement.js";
export { ChatStore } from "./ChatStore.js";
export { GroupStore } from "./GroupStore.js";
export { TimelineStore } from "./TimelineStore.js";
export type { TimelineAgentNode, TimelineDelta, TimelineState } from "./TimelineElement.js";
export { groupToolCalls } from "./groupToolCalls.js";
export { classifyToolName, describeSessionActivity } from "./describeSessionActivity.js";
export type { SessionActivityDescription, ToolCategory } from "./describeSessionActivity.js";
export { projectToolPresentation } from "./ToolPresentation.js";
export type {
    CommandPresentation,
    ExplorationPresentation,
    ExplorationStep,
    FileEditPresentation,
    TerminalInputPresentation,
    ToolPresentation,
} from "./ToolPresentation.js";
export { LiveStreamRefused, LiveStreamUnsupportedProtocol } from "./streamLiveEvents.js";
export { streamLiveEvents } from "./streamLiveEvents.js";
export type { LiveStreamHello, LiveStreamOptions } from "./streamLiveEvents.js";
export {
    CHECKING_SERVER_COMPATIBILITY,
    MAXIMUM_RIG_PROTOCOL_VERSION,
    MINIMUM_RIG_PROTOCOL_VERSION,
    describeServerCompatibility,
    serverCompatibility,
} from "./ServerCompatibility.js";
export type { ServerCompatibility } from "./ServerCompatibility.js";
export type {
    ActiveGroup,
    ActiveTurn,
    AgentAttachmentsElement,
    AgentTextElement,
    ChatDelta,
    ChatElement,
    CompactionElement,
    ConnectionState,
    FailureElement,
    GroupEndElement,
    GroupEndReason,
    InferenceElement,
    MutationAction,
    MutationRejectedDelta,
    SessionState,
    SessionUsage,
    SystemNoticeElement,
    ThinkingElement,
    ToolCallElement,
    ToolCallStatus,
    ToolPermissionReviewState,
    UserMessageElement,
} from "./ChatElement.js";
export type {
    GroupDelta,
    GroupSession,
    GroupsState,
    GroupUnread,
    GroupUsage,
    ProjectGroup,
    WorkspaceGroup,
} from "./GroupElement.js";
export { sessionUnreadAfterEvent } from "./sessionUnread.js";
export {
    HAPPY_CLOUD_CONTRACT_VERSION,
    HAPPY_CLOUD_CIPHERTEXT_MAX_LENGTH,
    happyCloudCapabilitySchema,
    happyCloudChangedEventSchema,
    happyCloudCommandErrorResponseSchema,
    happyCloudCommandResponseSchema,
    happyCloudCommandSchema,
    happyCloudConsentSchema,
    happyCloudProfileCiphertextResponseSchema,
    happyCloudSessionBlobResponseSchema,
    happyCloudStatusSchema,
    p2pPeerConnectionStatusSchema,
    p2pCredentialVisibilitySchema,
    p2pInstanceIdSchema,
    p2pPeerStatusSchema,
    p2pStatusChangedEventSchema,
    p2pStatusSchema,
    p2pTransportStatusSchema,
    CURRENT_ONBOARDING_VERSION,
    onboardMurmurRequestSchema,
    onboardMurmurResponseSchema,
    onboardingStatusSchema,
    createRigProfileRequestSchema,
    listRigProfilesResponseSchema,
    rigProfileChangedEventSchema,
    rigProfileEmailSchema,
    rigProfileIdSchema,
    rigProfilePhotoInputSchema,
    rigProfilePhotoSchema,
    rigProfileResponseSchema,
    rigProfileSchema,
    updateRigProfileRequestSchema,
    computePreparationNoticeSchema,
    computeServiceErrorSchema,
    FOLDER_ICON_MAX_LENGTH,
    FOLDER_NAME_MAX_LENGTH,
    FOLDER_TEXT_MAX_LENGTH,
    DOCUMENT_STATE_MAX_BYTES,
    DOCUMENT_UPDATE_MAX_BYTES,
    DOCUMENT_UPDATE_PAGE_MAX_LIMIT,
    DOCUMENT_UPDATE_RETENTION_MAX_BYTES,
    DOCUMENT_UPDATE_RETENTION_MAX_COUNT,
    createFolderRequestSchema,
    createFolderItemRequestSchema,
    createDocumentRequestSchema,
    documentCreatedBySchema,
    documentErrorCodeSchema,
    documentErrorResponseSchema,
    documentEventSchema,
    documentResponseSchema,
    documentSchema,
    documentUnreadCursorSchema,
    documentUpdatePageSchema,
    documentUpdateSchema,
    folderErrorResponseSchema,
    folderItemSchema,
    folderItemTargetSchema,
    folderResponseSchema,
    listDocumentUpdatesRequestSchema,
    listFoldersResponseSchema,
    folderSchema,
    moveFolderRequestSchema,
    moveFolderItemRequestSchema,
    moveSessionRequestSchema,
    updateFolderRequestSchema,
    PROJECT_WORKSPACE_ERROR_MAX_LENGTH,
    projectWorkspaceSchema,
    providerCredentialProvenanceSchema,
    SERVICE_NOTICE_MESSAGE_MAX_LENGTH,
    SERVICE_NOTICE_TEXT_MAX_LENGTH,
    serviceNoticeSchema,
    sessionScopeSchema,
    systemNoticePayloadSchema,
} from "./protocol.js";
export type {
    BackgroundProcess,
    BackgroundProcessSnapshot,
    DaemonIdentity,
    CreateFolderRequest,
    CreateFolderItemRequest,
    CreateDocumentRequest,
    Document,
    DocumentCreatedBy,
    DocumentErrorCode,
    DocumentErrorResponse,
    DocumentEvent,
    DocumentResponse,
    DocumentUpdate,
    DocumentUpdatePage,
    Folder,
    FolderErrorCode,
    FolderErrorResponse,
    FolderEvent,
    FolderItem,
    FolderItemResponse,
    FolderItemTarget,
    FolderResponse,
    ListFoldersResponse,
    ListDocumentUpdatesRequest,
    MoveFolderRequest,
    MoveFolderItemRequest,
    MoveSessionRequest,
    SessionScope,
    UpdateFolderRequest,
    WriteDocumentRequest,
    GitChangeSnapshot,
    ComputePreparationEvent,
    GlobalEvent,
    GlobalStreamHello,
    InterpretedSessionEvent,
    InboxUserInput,
    ModelSummary,
    McpServerSummary,
    ModelCatalog,
    ListPluginsResponse,
    ListWorkletsResponse,
    WorkletLogResponse,
    WorkletState,
    WorkletSummary,
    MutationId,
    PendingSteeringMessage,
    PluginLogResponse,
    PluginLogSnapshot,
    PluginSummary,
    PluginCategory,
    PluginIcon,
    ProviderModelCatalog,
    ProviderCredentialProvenance,
    P2pCredentialVisibility,
    PermissionReviewState,
    ProviderQuota,
    ProviderUsage,
    ProviderUsageCredits,
    ProviderUsageEntry,
    ProviderUsageWindow,
    RemoteTerminalGroupState,
    RemoteTerminalSummary,
    Project,
    ProjectCreator,
    ProjectRemoteSource,
    ProjectRegistrationErrorCode,
    ProjectWorkspace,
    SessionGoal,
    SessionContextUsage,
    SessionProviderQuota,
    SessionSummary,
    SessionActivity,
    SessionActivityKind,
    SessionActivityPermissionReview,
    SessionActivityWait,
    SessionAgentMetadata,
    SessionExecutionEnvironment,
    SessionInterruption,
    SessionTranscriptGroup,
    SessionTranscriptNotice,
    SessionUnreadReason,
    SessionUnreadState,
    SessionEvent,
    SessionStreamHello,
    SessionTask,
    ScheduledMessage,
    SessionUsageGroup,
    ComputePreparationNotice,
    ComputeServiceError,
    ServiceNotice,
    SystemNoticePayload,
    ShellCommandState,
    SubagentSummary,
    TimelineAgent,
    TimelineScope,
    TimelineSpan,
    TimelineSpanKind,
    TimelineSpanOutcome,
    FileDiff,
    FileDiffHunk,
    FileDiffLine,
    ToolCallPresentation,
    ToolResultPresentation,
    UserInputRequest,
    WorkflowRun,
} from "./protocol.js";
