//! The original startup discovery and persisted override behavior.
#[cfg(test)]
mod tests {
    use super::super::*;
    use crate::product::runtime::RuntimeModule;
    fn fixture(config:&str)->(tempfile::TempDir,Arc<ProviderScanModule>){let directory=tempfile::tempdir().unwrap();let home=directory.path().join(".happy");let public=directory.path().join(if cfg!(target_os="macos"){"Happy/Config"}else{"happy/config"});std::fs::create_dir_all(&public).unwrap();std::fs::write(public.join("happy.toml"),config).unwrap();let config=Arc::new(ConfigModule::isolated(&home).unwrap());config.prepare().unwrap();let lifecycle=Arc::new(LifecycleModule::new(config.clone()).unwrap());let runtime=Arc::new(RuntimeModule::new(config.clone()));let durable=Arc::new(DurableFunctionsModule::new(runtime,lifecycle.clone()).unwrap());let owner=ProviderScanModule::new(config,durable,lifecycle).unwrap();(directory,owner)}
    #[tokio::test]
    async fn positive_scan_is_remembered_and_missing_credentials_never_erase_it(){let (directory,owner)=fixture("[providers.fixture]\ntype='codex'\napi_key='fixture-placeholder'\ncredential_isolation=true\n");let scanned=owner.open().await.unwrap();let provider=scanned["providers"].as_array().unwrap().iter().find(|value|value["providerId"]=="fixture").unwrap();assert_eq!(provider["credentials"],"available");assert_eq!(provider["enablement"],"scan");assert_eq!(provider["enabled"],true);assert_eq!(owner.config.provider_auto_enable("fixture"),Some(true));let path=directory.path().join(if cfg!(target_os="macos"){"Happy/Config/happy.toml"}else{"happy/config/happy.toml"});std::fs::write(path,"[providers.fixture]\ntype='codex'\ncredential_isolation=true\n").unwrap();let config=Arc::new(ConfigModule::isolated(&directory.path().join(".happy")).unwrap());let lifecycle=Arc::new(LifecycleModule::new(config.clone()).unwrap());let runtime=Arc::new(RuntimeModule::new(config.clone()));let durable=Arc::new(DurableFunctionsModule::new(runtime,lifecycle.clone()).unwrap());let next=ProviderScanModule::new(config,durable,lifecycle).unwrap();next.load().await.unwrap();assert!(!next.config.provider_enabled("fixture"));let scan=next.scan().await.unwrap();let provider=scan["providers"].as_array().unwrap().iter().find(|value|value["providerId"]=="fixture").unwrap();assert_eq!(provider["credentials"],"missing");assert_eq!(provider["enabled"],true);assert_eq!(provider["remembered"],true);}
    #[tokio::test]
    async fn explicit_disable_and_auto_enable_false_survive_positive_credentials(){let (_directory,owner)=fixture("[providers.fixture]\ntype='codex'\napi_key='fixture-placeholder'\ncredential_isolation=true\nauto_enable=false\n");let scan=owner.open().await.unwrap();let provider=scan["providers"].as_array().unwrap().iter().find(|value|value["providerId"]=="fixture").unwrap();assert_eq!(provider["enablement"],"explicit");assert_eq!(provider["enabled"],false);assert_eq!(provider["remembered"],false);owner.set_overrides(&json!({"fixture":{"enabled":true}})).await.unwrap();assert!(owner.config.provider_enabled("fixture"));owner.set_overrides(&json!({"fixture":{"enabled":false}})).await.unwrap();owner.scan().await.unwrap();assert!(!owner.config.provider_enabled("fixture"));let before=std::fs::read(owner.config.paths.directory.join("runtime.toml")).unwrap();assert!(owner.set_overrides(&json!({"fixture":{"enabled":true},"missing":{"enabled":true}})).await.is_err());assert_eq!(std::fs::read(owner.config.paths.directory.join("runtime.toml")).unwrap(),before);assert!(!owner.config.provider_enabled("fixture"));}
}